// Generated from public/quran/quran-uthmani.json. 114 rows of surah
// metadata only, so server components (route metadata, sitemaps) can name a
// surah without pulling the 3 MB text payload into the worker bundle.

export type SurahIndexEntry = {
  id: number;
  nameArabic: string;
  nameEnglish: string;
  nameTranslation: string;
  revelationPlace: "meccan" | "medinan";
  ayahCount: number;
};

export const SURAH_INDEX: SurahIndexEntry[] = [
  { id: 1, nameArabic: "سُورَةُ ٱلْفَاتِحَةِ", nameEnglish: "Al-Faatiha", nameTranslation: "The Opening", revelationPlace: "meccan", ayahCount: 7 },
  { id: 2, nameArabic: "سُورَةُ البَقَرَةِ", nameEnglish: "Al-Baqara", nameTranslation: "The Cow", revelationPlace: "medinan", ayahCount: 286 },
  { id: 3, nameArabic: "سُورَةُ آلِ عِمۡرَانَ", nameEnglish: "Aal-i-Imraan", nameTranslation: "The Family of Imraan", revelationPlace: "medinan", ayahCount: 200 },
  { id: 4, nameArabic: "سُورَةُ النِّسَاءِ", nameEnglish: "An-Nisaa", nameTranslation: "The Women", revelationPlace: "medinan", ayahCount: 176 },
  { id: 5, nameArabic: "سُورَةُ المَائـِدَةِ", nameEnglish: "Al-Maaida", nameTranslation: "The Table", revelationPlace: "medinan", ayahCount: 120 },
  { id: 6, nameArabic: "سُورَةُ الأَنۡعَامِ", nameEnglish: "Al-An'aam", nameTranslation: "The Cattle", revelationPlace: "meccan", ayahCount: 165 },
  { id: 7, nameArabic: "سُورَةُ الأَعۡرَافِ", nameEnglish: "Al-A'raaf", nameTranslation: "The Heights", revelationPlace: "meccan", ayahCount: 206 },
  { id: 8, nameArabic: "سُورَةُ الأَنفَالِ", nameEnglish: "Al-Anfaal", nameTranslation: "The Spoils of War", revelationPlace: "medinan", ayahCount: 75 },
  { id: 9, nameArabic: "سُورَةُ التَّوۡبَةِ", nameEnglish: "At-Tawba", nameTranslation: "The Repentance", revelationPlace: "medinan", ayahCount: 129 },
  { id: 10, nameArabic: "سُورَةُ يُونُسَ", nameEnglish: "Yunus", nameTranslation: "Jonas", revelationPlace: "meccan", ayahCount: 109 },
  { id: 11, nameArabic: "سُورَةُ هُودٍ", nameEnglish: "Hud", nameTranslation: "Hud", revelationPlace: "meccan", ayahCount: 123 },
  { id: 12, nameArabic: "سُورَةُ يُوسُفَ", nameEnglish: "Yusuf", nameTranslation: "Joseph", revelationPlace: "meccan", ayahCount: 111 },
  { id: 13, nameArabic: "سُورَةُ الرَّعۡدِ", nameEnglish: "Ar-Ra'd", nameTranslation: "The Thunder", revelationPlace: "medinan", ayahCount: 43 },
  { id: 14, nameArabic: "سُورَةُ إِبۡرَاهِيمَ", nameEnglish: "Ibrahim", nameTranslation: "Abraham", revelationPlace: "meccan", ayahCount: 52 },
  { id: 15, nameArabic: "سُورَةُ الحِجۡرِ", nameEnglish: "Al-Hijr", nameTranslation: "The Rock", revelationPlace: "meccan", ayahCount: 99 },
  { id: 16, nameArabic: "سُورَةُ النَّحۡلِ", nameEnglish: "An-Nahl", nameTranslation: "The Bee", revelationPlace: "meccan", ayahCount: 128 },
  { id: 17, nameArabic: "سُورَةُ الإِسۡرَاءِ", nameEnglish: "Al-Israa", nameTranslation: "The Night Journey", revelationPlace: "meccan", ayahCount: 111 },
  { id: 18, nameArabic: "سُورَةُ الكَهۡفِ", nameEnglish: "Al-Kahf", nameTranslation: "The Cave", revelationPlace: "meccan", ayahCount: 110 },
  { id: 19, nameArabic: "سُورَةُ مَرۡيَمَ", nameEnglish: "Maryam", nameTranslation: "Mary", revelationPlace: "meccan", ayahCount: 98 },
  { id: 20, nameArabic: "سُورَةُ طه", nameEnglish: "Taa-Haa", nameTranslation: "Taa-Haa", revelationPlace: "meccan", ayahCount: 135 },
  { id: 21, nameArabic: "سُورَةُ الأَنبِيَاءِ", nameEnglish: "Al-Anbiyaa", nameTranslation: "The Prophets", revelationPlace: "meccan", ayahCount: 112 },
  { id: 22, nameArabic: "سُورَةُ الحَجِّ", nameEnglish: "Al-Hajj", nameTranslation: "The Pilgrimage", revelationPlace: "medinan", ayahCount: 78 },
  { id: 23, nameArabic: "سُورَةُ المُؤۡمِنُونَ", nameEnglish: "Al-Muminoon", nameTranslation: "The Believers", revelationPlace: "meccan", ayahCount: 118 },
  { id: 24, nameArabic: "سُورَةُ النُّورِ", nameEnglish: "An-Noor", nameTranslation: "The Light", revelationPlace: "medinan", ayahCount: 64 },
  { id: 25, nameArabic: "سُورَةُ الفُرۡقَانِ", nameEnglish: "Al-Furqaan", nameTranslation: "The Criterion", revelationPlace: "meccan", ayahCount: 77 },
  { id: 26, nameArabic: "سُورَةُ الشُّعَرَاءِ", nameEnglish: "Ash-Shu'araa", nameTranslation: "The Poets", revelationPlace: "meccan", ayahCount: 227 },
  { id: 27, nameArabic: "سُورَةُ النَّمۡلِ", nameEnglish: "An-Naml", nameTranslation: "The Ant", revelationPlace: "meccan", ayahCount: 93 },
  { id: 28, nameArabic: "سُورَةُ القَصَصِ", nameEnglish: "Al-Qasas", nameTranslation: "The Stories", revelationPlace: "meccan", ayahCount: 88 },
  { id: 29, nameArabic: "سُورَةُ العَنكَبُوتِ", nameEnglish: "Al-Ankaboot", nameTranslation: "The Spider", revelationPlace: "meccan", ayahCount: 69 },
  { id: 30, nameArabic: "سُورَةُ الرُّومِ", nameEnglish: "Ar-Room", nameTranslation: "The Romans", revelationPlace: "meccan", ayahCount: 60 },
  { id: 31, nameArabic: "سُورَةُ لُقۡمَانَ", nameEnglish: "Luqman", nameTranslation: "Luqman", revelationPlace: "meccan", ayahCount: 34 },
  { id: 32, nameArabic: "سُورَةُ السَّجۡدَةِ", nameEnglish: "As-Sajda", nameTranslation: "The Prostration", revelationPlace: "meccan", ayahCount: 30 },
  { id: 33, nameArabic: "سُورَةُ الأَحۡزَابِ", nameEnglish: "Al-Ahzaab", nameTranslation: "The Clans", revelationPlace: "medinan", ayahCount: 73 },
  { id: 34, nameArabic: "سُورَةُ سَبَإٍ", nameEnglish: "Saba", nameTranslation: "Sheba", revelationPlace: "meccan", ayahCount: 54 },
  { id: 35, nameArabic: "سُورَةُ فَاطِرٍ", nameEnglish: "Faatir", nameTranslation: "The Originator", revelationPlace: "meccan", ayahCount: 45 },
  { id: 36, nameArabic: "سُورَةُ يسٓ", nameEnglish: "Yaseen", nameTranslation: "Yaseen", revelationPlace: "meccan", ayahCount: 83 },
  { id: 37, nameArabic: "سُورَةُ الصَّافَّاتِ", nameEnglish: "As-Saaffaat", nameTranslation: "Those drawn up in Ranks", revelationPlace: "meccan", ayahCount: 182 },
  { id: 38, nameArabic: "سُورَةُ صٓ", nameEnglish: "Saad", nameTranslation: "The letter Saad", revelationPlace: "meccan", ayahCount: 88 },
  { id: 39, nameArabic: "سُورَةُ الزُّمَرِ", nameEnglish: "Az-Zumar", nameTranslation: "The Groups", revelationPlace: "meccan", ayahCount: 75 },
  { id: 40, nameArabic: "سُورَةُ غَافِرٍ", nameEnglish: "Ghafir", nameTranslation: "The Forgiver", revelationPlace: "meccan", ayahCount: 85 },
  { id: 41, nameArabic: "سُورَةُ فُصِّلَتۡ", nameEnglish: "Fussilat", nameTranslation: "Explained in detail", revelationPlace: "meccan", ayahCount: 54 },
  { id: 42, nameArabic: "سُورَةُ الشُّورَىٰ", nameEnglish: "Ash-Shura", nameTranslation: "Consultation", revelationPlace: "meccan", ayahCount: 53 },
  { id: 43, nameArabic: "سُورَةُ الزُّخۡرُفِ", nameEnglish: "Az-Zukhruf", nameTranslation: "Ornaments of gold", revelationPlace: "meccan", ayahCount: 89 },
  { id: 44, nameArabic: "سُورَةُ الدُّخَانِ", nameEnglish: "Ad-Dukhaan", nameTranslation: "The Smoke", revelationPlace: "meccan", ayahCount: 59 },
  { id: 45, nameArabic: "سُورَةُ الجَاثِيَةِ", nameEnglish: "Al-Jaathiya", nameTranslation: "Crouching", revelationPlace: "meccan", ayahCount: 37 },
  { id: 46, nameArabic: "سُورَةُ الأَحۡقَافِ", nameEnglish: "Al-Ahqaf", nameTranslation: "The Dunes", revelationPlace: "meccan", ayahCount: 35 },
  { id: 47, nameArabic: "سُورَةُ مُحَمَّدٍ", nameEnglish: "Muhammad", nameTranslation: "Muhammad", revelationPlace: "medinan", ayahCount: 38 },
  { id: 48, nameArabic: "سُورَةُ الفَتۡحِ", nameEnglish: "Al-Fath", nameTranslation: "The Victory", revelationPlace: "medinan", ayahCount: 29 },
  { id: 49, nameArabic: "سُورَةُ الحُجُرَاتِ", nameEnglish: "Al-Hujuraat", nameTranslation: "The Inner Apartments", revelationPlace: "medinan", ayahCount: 18 },
  { id: 50, nameArabic: "سُورَةُ قٓ", nameEnglish: "Qaaf", nameTranslation: "The letter Qaaf", revelationPlace: "meccan", ayahCount: 45 },
  { id: 51, nameArabic: "سُورَةُ الذَّارِيَاتِ", nameEnglish: "Adh-Dhaariyat", nameTranslation: "The Winnowing Winds", revelationPlace: "meccan", ayahCount: 60 },
  { id: 52, nameArabic: "سُورَةُ الطُّورِ", nameEnglish: "At-Tur", nameTranslation: "The Mount", revelationPlace: "meccan", ayahCount: 49 },
  { id: 53, nameArabic: "سُورَةُ النَّجۡمِ", nameEnglish: "An-Najm", nameTranslation: "The Star", revelationPlace: "meccan", ayahCount: 62 },
  { id: 54, nameArabic: "سُورَةُ القَمَرِ", nameEnglish: "Al-Qamar", nameTranslation: "The Moon", revelationPlace: "meccan", ayahCount: 55 },
  { id: 55, nameArabic: "سُورَةُ الرَّحۡمَٰن", nameEnglish: "Ar-Rahmaan", nameTranslation: "The Beneficent", revelationPlace: "medinan", ayahCount: 78 },
  { id: 56, nameArabic: "سُورَةُ الوَاقِعَةِ", nameEnglish: "Al-Waaqia", nameTranslation: "The Inevitable", revelationPlace: "meccan", ayahCount: 96 },
  { id: 57, nameArabic: "سُورَةُ الحَدِيدِ", nameEnglish: "Al-Hadid", nameTranslation: "The Iron", revelationPlace: "medinan", ayahCount: 29 },
  { id: 58, nameArabic: "سُورَةُ المُجَادلَةِ", nameEnglish: "Al-Mujaadila", nameTranslation: "The Pleading Woman", revelationPlace: "medinan", ayahCount: 22 },
  { id: 59, nameArabic: "سُورَةُ الحَشۡرِ", nameEnglish: "Al-Hashr", nameTranslation: "The Exile", revelationPlace: "medinan", ayahCount: 24 },
  { id: 60, nameArabic: "سُورَةُ المُمۡتَحنَةِ", nameEnglish: "Al-Mumtahana", nameTranslation: "She that is to be examined", revelationPlace: "medinan", ayahCount: 13 },
  { id: 61, nameArabic: "سُورَةُ الصَّفِّ", nameEnglish: "As-Saff", nameTranslation: "The Ranks", revelationPlace: "medinan", ayahCount: 14 },
  { id: 62, nameArabic: "سُورَةُ الجُمُعَةِ", nameEnglish: "Al-Jumu'a", nameTranslation: "Friday", revelationPlace: "medinan", ayahCount: 11 },
  { id: 63, nameArabic: "سُورَةُ المُنَافِقُونَ", nameEnglish: "Al-Munaafiqoon", nameTranslation: "The Hypocrites", revelationPlace: "medinan", ayahCount: 11 },
  { id: 64, nameArabic: "سُورَةُ التَّغَابُنِ", nameEnglish: "At-Taghaabun", nameTranslation: "Mutual Disillusion", revelationPlace: "medinan", ayahCount: 18 },
  { id: 65, nameArabic: "سُورَةُ الطَّلَاقِ", nameEnglish: "At-Talaaq", nameTranslation: "Divorce", revelationPlace: "medinan", ayahCount: 12 },
  { id: 66, nameArabic: "سُورَةُ التَّحۡرِيمِ", nameEnglish: "At-Tahrim", nameTranslation: "The Prohibition", revelationPlace: "medinan", ayahCount: 12 },
  { id: 67, nameArabic: "سُورَةُ المُلۡكِ", nameEnglish: "Al-Mulk", nameTranslation: "The Sovereignty", revelationPlace: "meccan", ayahCount: 30 },
  { id: 68, nameArabic: "سُورَةُ القَلَمِ", nameEnglish: "Al-Qalam", nameTranslation: "The Pen", revelationPlace: "meccan", ayahCount: 52 },
  { id: 69, nameArabic: "سُورَةُ الحَاقَّةِ", nameEnglish: "Al-Haaqqa", nameTranslation: "The Reality", revelationPlace: "meccan", ayahCount: 52 },
  { id: 70, nameArabic: "سُورَةُ المَعَارِجِ", nameEnglish: "Al-Ma'aarij", nameTranslation: "The Ascending Stairways", revelationPlace: "meccan", ayahCount: 44 },
  { id: 71, nameArabic: "سُورَةُ نُوحٍ", nameEnglish: "Nooh", nameTranslation: "Noah", revelationPlace: "meccan", ayahCount: 28 },
  { id: 72, nameArabic: "سُورَةُ الجِنِّ", nameEnglish: "Al-Jinn", nameTranslation: "The Jinn", revelationPlace: "meccan", ayahCount: 28 },
  { id: 73, nameArabic: "سُورَةُ المُزَّمِّلِ", nameEnglish: "Al-Muzzammil", nameTranslation: "The Enshrouded One", revelationPlace: "meccan", ayahCount: 20 },
  { id: 74, nameArabic: "سُورَةُ المُدَّثِّرِ", nameEnglish: "Al-Muddaththir", nameTranslation: "The Cloaked One", revelationPlace: "meccan", ayahCount: 56 },
  { id: 75, nameArabic: "سُورَةُ القِيَامَةِ", nameEnglish: "Al-Qiyaama", nameTranslation: "The Resurrection", revelationPlace: "meccan", ayahCount: 40 },
  { id: 76, nameArabic: "سُورَةُ الإِنسَانِ", nameEnglish: "Al-Insaan", nameTranslation: "Man", revelationPlace: "medinan", ayahCount: 31 },
  { id: 77, nameArabic: "سُورَةُ المُرۡسَلَاتِ", nameEnglish: "Al-Mursalaat", nameTranslation: "The Emissaries", revelationPlace: "meccan", ayahCount: 50 },
  { id: 78, nameArabic: "سُورَةُ النَّبَإِ", nameEnglish: "An-Naba", nameTranslation: "The Announcement", revelationPlace: "meccan", ayahCount: 40 },
  { id: 79, nameArabic: "سُورَةُ النَّازِعَاتِ", nameEnglish: "An-Naazi'aat", nameTranslation: "Those who drag forth", revelationPlace: "meccan", ayahCount: 46 },
  { id: 80, nameArabic: "سُورَةُ عَبَسَ", nameEnglish: "Abasa", nameTranslation: "He frowned", revelationPlace: "meccan", ayahCount: 42 },
  { id: 81, nameArabic: "سُورَةُ التَّكۡوِيرِ", nameEnglish: "At-Takwir", nameTranslation: "The Overthrowing", revelationPlace: "meccan", ayahCount: 29 },
  { id: 82, nameArabic: "سُورَةُ الانفِطَارِ", nameEnglish: "Al-Infitaar", nameTranslation: "The Cleaving", revelationPlace: "meccan", ayahCount: 19 },
  { id: 83, nameArabic: "سُورَةُ المُطَفِّفِينَ", nameEnglish: "Al-Mutaffifin", nameTranslation: "Defrauding", revelationPlace: "meccan", ayahCount: 36 },
  { id: 84, nameArabic: "سُورَةُ الانشِقَاقِ", nameEnglish: "Al-Inshiqaaq", nameTranslation: "The Splitting Open", revelationPlace: "meccan", ayahCount: 25 },
  { id: 85, nameArabic: "سُورَةُ البُرُوجِ", nameEnglish: "Al-Burooj", nameTranslation: "The Constellations", revelationPlace: "meccan", ayahCount: 22 },
  { id: 86, nameArabic: "سُورَةُ الطَّارِقِ", nameEnglish: "At-Taariq", nameTranslation: "The Morning Star", revelationPlace: "meccan", ayahCount: 17 },
  { id: 87, nameArabic: "سُورَةُ الأَعۡلَىٰ", nameEnglish: "Al-A'laa", nameTranslation: "The Most High", revelationPlace: "meccan", ayahCount: 19 },
  { id: 88, nameArabic: "سُورَةُ الغَاشِيَةِ", nameEnglish: "Al-Ghaashiya", nameTranslation: "The Overwhelming", revelationPlace: "meccan", ayahCount: 26 },
  { id: 89, nameArabic: "سُورَةُ الفَجۡرِ", nameEnglish: "Al-Fajr", nameTranslation: "The Dawn", revelationPlace: "meccan", ayahCount: 30 },
  { id: 90, nameArabic: "سُورَةُ البَلَدِ", nameEnglish: "Al-Balad", nameTranslation: "The City", revelationPlace: "meccan", ayahCount: 20 },
  { id: 91, nameArabic: "سُورَةُ الشَّمۡسِ", nameEnglish: "Ash-Shams", nameTranslation: "The Sun", revelationPlace: "meccan", ayahCount: 15 },
  { id: 92, nameArabic: "سُورَةُ اللَّيۡلِ", nameEnglish: "Al-Lail", nameTranslation: "The Night", revelationPlace: "meccan", ayahCount: 21 },
  { id: 93, nameArabic: "سُورَةُ الضُّحَىٰ", nameEnglish: "Ad-Dhuhaa", nameTranslation: "The Morning Hours", revelationPlace: "meccan", ayahCount: 11 },
  { id: 94, nameArabic: "سُورَةُ الشَّرۡحِ", nameEnglish: "Ash-Sharh", nameTranslation: "The Consolation", revelationPlace: "meccan", ayahCount: 8 },
  { id: 95, nameArabic: "سُورَةُ التِّينِ", nameEnglish: "At-Tin", nameTranslation: "The Fig", revelationPlace: "meccan", ayahCount: 8 },
  { id: 96, nameArabic: "سُورَةُ العَلَقِ", nameEnglish: "Al-Alaq", nameTranslation: "The Clot", revelationPlace: "meccan", ayahCount: 19 },
  { id: 97, nameArabic: "سُورَةُ القَدۡرِ", nameEnglish: "Al-Qadr", nameTranslation: "The Power, Fate", revelationPlace: "meccan", ayahCount: 5 },
  { id: 98, nameArabic: "سُورَةُ البَيِّنَةِ", nameEnglish: "Al-Bayyina", nameTranslation: "The Evidence", revelationPlace: "medinan", ayahCount: 8 },
  { id: 99, nameArabic: "سُورَةُ الزَّلۡزَلَةِ", nameEnglish: "Az-Zalzala", nameTranslation: "The Earthquake", revelationPlace: "medinan", ayahCount: 8 },
  { id: 100, nameArabic: "سُورَةُ العَادِيَاتِ", nameEnglish: "Al-Aadiyaat", nameTranslation: "The Chargers", revelationPlace: "meccan", ayahCount: 11 },
  { id: 101, nameArabic: "سُورَةُ القَارِعَةِ", nameEnglish: "Al-Qaari'a", nameTranslation: "The Calamity", revelationPlace: "meccan", ayahCount: 11 },
  { id: 102, nameArabic: "سُورَةُ التَّكَاثُرِ", nameEnglish: "At-Takaathur", nameTranslation: "Competition", revelationPlace: "meccan", ayahCount: 8 },
  { id: 103, nameArabic: "سُورَةُ العَصۡرِ", nameEnglish: "Al-Asr", nameTranslation: "The Declining Day, Epoch", revelationPlace: "meccan", ayahCount: 3 },
  { id: 104, nameArabic: "سُورَةُ الهُمَزَةِ", nameEnglish: "Al-Humaza", nameTranslation: "The Traducer", revelationPlace: "meccan", ayahCount: 9 },
  { id: 105, nameArabic: "سُورَةُ الفِيلِ", nameEnglish: "Al-Fil", nameTranslation: "The Elephant", revelationPlace: "meccan", ayahCount: 5 },
  { id: 106, nameArabic: "سُورَةُ قُرَيۡشٍ", nameEnglish: "Quraish", nameTranslation: "Quraysh", revelationPlace: "meccan", ayahCount: 4 },
  { id: 107, nameArabic: "سُورَةُ المَاعُونِ", nameEnglish: "Al-Maa'un", nameTranslation: "Almsgiving", revelationPlace: "meccan", ayahCount: 7 },
  { id: 108, nameArabic: "سُورَةُ الكَوۡثَرِ", nameEnglish: "Al-Kawthar", nameTranslation: "Abundance", revelationPlace: "meccan", ayahCount: 3 },
  { id: 109, nameArabic: "سُورَةُ الكَافِرُونَ", nameEnglish: "Al-Kaafiroon", nameTranslation: "The Disbelievers", revelationPlace: "meccan", ayahCount: 6 },
  { id: 110, nameArabic: "سُورَةُ النَّصۡرِ", nameEnglish: "An-Nasr", nameTranslation: "Divine Support", revelationPlace: "medinan", ayahCount: 3 },
  { id: 111, nameArabic: "سُورَةُ المَسَدِ", nameEnglish: "Al-Masad", nameTranslation: "The Palm Fibre", revelationPlace: "meccan", ayahCount: 5 },
  { id: 112, nameArabic: "سُورَةُ الإِخۡلَاصِ", nameEnglish: "Al-Ikhlaas", nameTranslation: "Sincerity", revelationPlace: "meccan", ayahCount: 4 },
  { id: 113, nameArabic: "سُورَةُ الفَلَقِ", nameEnglish: "Al-Falaq", nameTranslation: "The Dawn", revelationPlace: "meccan", ayahCount: 5 },
  { id: 114, nameArabic: "سُورَةُ النَّاسِ", nameEnglish: "An-Naas", nameTranslation: "Mankind", revelationPlace: "meccan", ayahCount: 6 },
];

export function getSurahIndexEntry(id: number): SurahIndexEntry | undefined {
  return SURAH_INDEX[id - 1];
}
