// Word-by-word English translation accessor for the mushaf hover tooltips.
//
// Data: /quran/word-by-word/s001..s114.json, generated by
// scripts/build-wbw-assets.mjs from the repo's snapshot of the
// Dr. Shehnaz Shaikh and Ms. Kausar Khatri translation (free for any halaal
// use; attribution in the settings drawer and in
// public/quran/word-by-word/SOURCE.txt). The build patch guarantees
// wbw.p === QPC layout glyph position 1:1 for every type:"word" glyph.
//
// Static fetch, no /api proxy (unlike tajweed, which proxies an external
// API): Cloudflare gives edge caching + brotli for free on /quran/*.

export type WbwWord = {
  p: number;
  a: string;
  e: string;
  /** Transliteration: reserved; ships only after a license-verified regen. */
  t?: string;
};

export type WbwSurahMap = Record<string, WbwWord[]>;

// Bump when the files regenerate with a shape change (e.g. adding "t") so
// stale localStorage copies are bypassed.
export const WBW_CACHE_VERSION = 1;

export const wbwStorageKey = (surahId: number) =>
  `ilm-quran:wbw:${WBW_CACHE_VERSION}:${surahId}`;

export async function fetchSurahWbw(surahId: number): Promise<WbwSurahMap> {
  const response = await fetch(
    `/quran/word-by-word/s${String(surahId).padStart(3, "0")}.json`
  );
  if (!response.ok) {
    throw new Error(`Word-by-word request failed: ${response.status}`);
  }
  return (await response.json()) as WbwSurahMap;
}
